export { default as Home } from './home/Home'
export { default as Posts } from './posts/Posts'
export { default as PostDetails } from './posts/PostDetails'
export { default as Users } from './users/Users'
export { default as UserDetails } from './users/UserDetails'